# Generated by Django 3.2 on 2021-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etag', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
                ('accessRole', models.CharField(max_length=100)),
                ('timeZone', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
